name: Just run ENV
on: workflow_dispatch

jobs:
  run-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run script env
        env:
          GREETING_USER: "Gurult"
        run: python3 script.py
